<a href="https://colab.research.google.com/github/santiagovillamizarjaimes-collab/programaci-n-I/blob/main/base_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Base de datos

In [2]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()

Saving f_capitulos.csv to f_capitulos.csv

In [4]:
import io
f_capitulos1 = io.BytesIO(uploaded['f_capitulos.csv'])
f_capitulos1 = pd.read_csv(f_capitulos1, sep = ",", encoding = "latin-1")
f_capitulos1.head(4)

,F_01,F_01_CUAL,F_02,F_02_CUAL,F_03,F_04,F_05,F_06,F_07,F_08,...,F_18,F_19,F_20,F_20_CUAL,F_21,F_21_CUAL,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN
0,2,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,2
1,2,NaN,2,NaN,1,18.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,1,1,1
2,2,NaN,2,NaN,1,20.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,1,1,1
3,2,NaN,2,NaN,1,20.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,1,1,1

In [5]:
tabla_alcohol = pd.DataFrame({
    'edad': f_capitulos1['F_04'],
    'borrachera': f_capitulos1['F_09'],
    'cerveza': f_capitulos1['F_10_A'],
    'recordar': f_capitulos1['F_19'],
    'herido': f_capitulos1['F_20_CUAL'],
    'preocupacion': f_capitulos1['F_21_CUAL'],
    'familia': f_capitulos1["F_01_CUAL"],
    'amigos': f_capitulos1['F_02_CUAL'],
})
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         NaN      NaN       NaN     NaN           NaN      NaN     NaN
1  18.0         NaN      NaN       NaN     NaN           NaN      NaN     NaN
2  20.0         NaN      NaN       NaN     NaN           NaN      NaN     NaN
3  20.0         NaN      NaN       NaN     NaN           NaN      NaN     NaN
4  20.0         NaN      NaN       NaN     NaN           NaN      NaN     NaN

In [6]:
tabla_alcohol['cerveza'] = tabla_alcohol['cerveza'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         NaN      0.0       NaN     NaN           NaN      NaN     NaN
1  18.0         NaN      0.0       NaN     NaN           NaN      NaN     NaN
2  20.0         NaN      0.0       NaN     NaN           NaN      NaN     NaN
3  20.0         NaN      0.0       NaN     NaN           NaN      NaN     NaN
4  20.0         NaN      0.0       NaN     NaN           NaN      NaN     NaN

In [7]:
tabla_alcohol['borrachera'] = tabla_alcohol['borrachera'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       NaN     NaN           NaN      NaN     NaN
1  18.0         0.0      0.0       NaN     NaN           NaN      NaN     NaN
2  20.0         0.0      0.0       NaN     NaN           NaN      NaN     NaN
3  20.0         0.0      0.0       NaN     NaN           NaN      NaN     NaN
4  20.0         0.0      0.0       NaN     NaN           NaN      NaN     NaN

In [9]:
tabla_alcohol['recordar'] = tabla_alcohol['recordar'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       0.0     NaN           NaN      NaN     NaN
1  18.0         0.0      0.0       0.0     NaN           NaN      NaN     NaN
2  20.0         0.0      0.0       0.0     NaN           NaN      NaN     NaN
3  20.0         0.0      0.0       0.0     NaN           NaN      NaN     NaN
4  20.0         0.0      0.0       0.0     NaN           NaN      NaN     NaN

In [10]:
tabla_alcohol['herido'] = tabla_alcohol['herido'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       0.0     0.0           NaN      NaN     NaN
1  18.0         0.0      0.0       0.0     0.0           NaN      NaN     NaN
2  20.0         0.0      0.0       0.0     0.0           NaN      NaN     NaN
3  20.0         0.0      0.0       0.0     0.0           NaN      NaN     NaN
4  20.0         0.0      0.0       0.0     0.0           NaN      NaN     NaN

In [11]:
tabla_alcohol['preocupacion'] = tabla_alcohol['preocupacion'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       0.0     0.0           0.0      NaN     NaN
1  18.0         0.0      0.0       0.0     0.0           0.0      NaN     NaN
2  20.0         0.0      0.0       0.0     0.0           0.0      NaN     NaN
3  20.0         0.0      0.0       0.0     0.0           0.0      NaN     NaN
4  20.0         0.0      0.0       0.0     0.0           0.0      NaN     NaN

In [12]:
tabla_alcohol['familia'] = tabla_alcohol['familia'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       0.0     0.0           0.0      0.0     NaN
1  18.0         0.0      0.0       0.0     0.0           0.0      0.0     NaN
2  20.0         0.0      0.0       0.0     0.0           0.0      0.0     NaN
3  20.0         0.0      0.0       0.0     0.0           0.0      0.0     NaN
4  20.0         0.0      0.0       0.0     0.0           0.0      0.0     NaN

In [13]:
tabla_alcohol['amigos'] = tabla_alcohol['amigos'].fillna(0)
tabla_alcohol.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
0   NaN         0.0      0.0       0.0     0.0           0.0      0.0     0.0
1  18.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
2  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
3  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
4  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0

In [15]:
tabla_alcohol1 = tabla_alcohol.dropna()
tabla_alcohol1.head(5)

   edad  borrachera  cerveza  recordar  herido  preocupacion  familia  amigos
1  18.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
2  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
3  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
4  20.0         0.0      0.0       0.0     0.0           0.0      0.0     0.0
5  16.0         0.0      3.0       1.0     2.0           0.0      0.0     0.0

In [16]:
tabla_alcohol1['cerveza'] = tabla_alcohol1['cerveza'].astype(str)
tabla_alcohol1['recordar'] = tabla_alcohol1['recordar'].astype(str)
tabla_alcohol1['herido'] = tabla_alcohol1['herido'].astype(str)
tabla_alcohol1['familia'] = tabla_alcohol1['familia'].astype(str)
tabla_alcohol1['amigos'] = tabla_alcohol1['amigos'].astype(str)
tabla_alcohol1['preocupacion'] = tabla_alcohol1['preocupacion'].astype(str)

/tmp/ipykernel_5558/3496368803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['cerveza'] = tabla_alcohol1['cerveza'].astype(str)
/tmp/ipykernel_5558/3496368803.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['recordar'] = tabla_alcohol1['recordar'].astype(str)
/tmp/ipykernel_5558/3496368803.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['herido'] = tabla_alcohol1['herido'].astype(str)
/tmp/ipykernel_5558/3496368803.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['familia'] = tabla_alcohol1['familia'].astype(str)
/tmp/ipykernel_5558/3496368803.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['amigos'] = tabla_alcohol1['amigos'].astype(str)
/tmp/ipykernel_5558/3496368803.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabla_alcohol1['preocupacion'] = tabla_alcohol1['preocupacion'].astype(str)